# Generated by Django 5.0.6 on 2024-08-06 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question_text', models.CharField(max_length=128)),
                ('question_type', models.CharField(choices=[('MCQ', 'MCQ'), ('FIB', 'FIB'), ('SQL', 'SQL')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('branch', models.ManyToManyField(to='exam_management.branch')),
                ('registered_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam_management.user')),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('option_text', models.TextField(blank=True, null=True)),
                ('is_correct', models.BooleanField(blank=True, default=False, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam_management.question')),
            ],
        ),
        migrations.CreateModel(
            name='FillInTheBlankAnswer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('correct_answer', models.TextField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam_management.question')),
            ],
        ),
        migrations.CreateModel(
            name='SqlQuery',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('expected_answer', models.TextField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam_management.question')),
            ],
        ),
        migrations.AddField(
            model_name='branch',
            name='stream',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam_management.stream'),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=128)),
                ('rollno', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=100)),
                ('highestdegree', models.CharField(max_length=100)),
                ('phone_no', models.CharField(max_length=10)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exam_management.branch')),
                ('college', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exam_management.college')),
                ('stream', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exam_management.stream')),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('is_open', models.BooleanField(default=True)),
                ('has_sql', models.BooleanField(default=False)),
                ('db_name', models.CharField(blank=True, max_length=100, null=True)),
                ('sql_script', models.TextField(blank=True, null=True)),
                ('branches', models.ManyToManyField(related_name='tests', to='exam_management.branch')),
                ('stream', models.ManyToManyField(related_name='tests', to='exam_management.stream')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam_management.user')),
            ],
        ),
        migrations.CreateModel(
            name='StudentTest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('eligible', models.BooleanField(default=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam_management.student')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam_management.test')),
            ],
            options={
                'unique_together': {('student', 'test')},
            },
        ),
        migrations.AddField(
            model_name='question',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam_management.test'),
        ),
        migrations.AlterUniqueTogether(
            name='branch',
            unique_together={('name', 'stream')},
        ),
        migrations.CreateModel(
            name='StudentAnswer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text_answer', models.TextField(blank=True, null=True)),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('is_correct', models.BooleanField(null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam_management.question')),
                ('student_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam_management.studenttest')),
            ],
            options={
                'unique_together': {('student_test', 'question')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='question',
            unique_together={('question_text', 'test')},
        ),
    ]
