# Generated by Django 5.0.6 on 2024-07-12 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studenttest',
            name='eligible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='test',
            name='has_eligibility_criteria',
            field=models.BooleanField(default=False),
        ),
    ]
