# Generated by Django 5.0.6 on 2024-08-08 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_management', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='collegestream',
            constraint=models.UniqueConstraint(fields=('college', 'stream'), name='unique_college_stream'),
        ),
    ]
