# Generated by Django 5.0.6 on 2024-08-16 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_management', '0002_collegestream_unique_college_stream'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='question',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='college',
            unique_together={('name', 'address')},
        ),
        migrations.AddField(
            model_name='question',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='questions', to='exam_management.tag'),
        ),
        migrations.RemoveField(
            model_name='question',
            name='test',
        ),
        migrations.CreateModel(
            name='TestQuestion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam_management.question')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam_management.test')),
            ],
            options={
                'unique_together': {('test', 'question')},
            },
        ),
    ]
